# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: PR Validation

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      # --------------------------
      # 1. Install Hugo
      # --------------------------
      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.128.0/hugo_extended_0.128.0_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      # --------------------------
      # 2. Get PR Code
      # --------------------------
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Important for Hugo themes
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout PR commit

      # --------------------------
      # 3. Build Site
      # --------------------------
      - name: Build with Hugo
        run: |
          hugo --minify --buildDrafts --buildFuture
          # --minify: Test production build
          # --buildDrafts: Check draft posts
          # --buildFuture: Verify scheduled posts

      # --------------------------
      # 4. Integrity Checks
      # --------------------------
      - name: Verify Build Output
        run: |
          # Check public directory exists
          if [ ! -d "./public" ]; then
            echo "❌ Error: No public directory generated"
            exit 1
          fi

          # Check for HTML files
          HTML_COUNT=$(find ./public -name "*.html" | wc -l)
          if [ "$HTML_COUNT" -eq 0 ]; then
            echo "❌ Error: No HTML files generated"
            exit 1
          fi

          [ -f "./public/index.html" ] || (echo "❌ Missing index.html" && exit 1)
          [ -f "./public/404.html" ] || echo "⚠️ Warning: 404 page missing"

      # --------------------------
      # Optional: Link Checker
      # --------------------------
      - name: Check Links (Optional)
        continue-on-error: true  # Don't block PR for broken links
        run: |
          # Install link checker
          sudo apt-get install -y lychee
          
          # Check internal links only
          lychee --base ./public ./public/**/*.html